version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=job-tracker-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - ./api/sql/db.sql:/docker-entrypoint-initdb.d/init.sql
  api:
   build: ./api
   environment:
      - DEV_ENV=postgresql://postgres:P%40ssw0rd@db:5432/job-tracker-db
      - SECRET=GREENBEAR
   ports:
     - 8080:8080
   depends_on:
     - db
  nginx:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - db
      - api
