version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=job-tracker-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - ./api/sql/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - job-app-tracker_default
  api:
    build: ./api
    container_name: job-apps-tracker-api
    environment:
      - DEV_ENV=postgresql://postgres:P%40ssw0rd@db:5432/job-tracker-db
      - SECRET=GREENBEAR
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - nginx_network
      - job-app-tracker_default
  frontend:
    build: ./frontend
    container_name: job-apps-tracker-frontend
    ports:
      - 3000:3000
    depends_on:
      - db
      - api
    networks:
      - nginx_network
      - job-app-tracker_default
networks:
  nginx_network:
    external: true
  job-app-tracker_default: