services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  nginx_network:
    external: true