image: python:3.10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/

stages:
  - build
  - test
  - lint
  - package

build:
  stage: build
  script:
    - pip install virtualenv
    - virtualenv venv/
    - source venv/bin/activate
    - pip install -r api/requirements.txt
  rules:
    - changes:
      - api/*

test:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv/
    - source venv/bin/activate
  script:
    - cd api/
    - pytest test*.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: api/report.xml
  rules:
    - changes:
      - api/*

lint:
  stage: lint
  before_script:
    - pip install virtualenv
    - virtualenv venv/
    - source venv/bin/activate
  script:
    - pylint --fail-under 7.0 api/app.py
  rules:
    - changes:
      - api/*

package python files:
  stage: package
  image: alpine
  cache: []
  script:
    - apk --no-cache add zip
    - zip api/artifacts.zip api/*.py -x api/test*.py

  artifacts:
    paths:
      - api/artifacts.zip
  rules:
    - changes:
      - api/*
