image: python:3.10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - frontend/node_modules

stages:
  - build
  - test
  - lint
  - package
  - dockerize
  - deploy

build api:
  stage: build
  script:
    - pip install virtualenv
    - virtualenv venv/
    - source venv/bin/activate
    - pip install -r api/requirements.txt
    - cd api/sql
    - python3 create_tables.py
  rules:
    - changes:
      - api/*
  artifacts:
    paths:
      - api/api.db
    expire_in: 10 mins

build frontend:
  stage: build
  image: node:14
  script:
    - cd frontend/
    - npm install
    - npm run build
    - mv build/ ..
  rules:
    - changes:
      - frontend/*

test:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv/
    - source venv/bin/activate
  script:
    - cd api/
    - pytest test*.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: api/report.xml
  rules:
    - changes:
      - api/*

lint:
  stage: lint
  before_script:
    - pip install virtualenv
    - virtualenv venv/
    - source venv/bin/activate
  script:
    - pylint --fail-under 8.0 api/app.py
  rules:
    - changes:
      - api/*

package python files:
  stage: package
  image: alpine
  cache: []
  script:
    - apk --no-cache add zip
    - zip api/artifacts.zip api/*.py -x api/test*.py

  artifacts:
    paths:
      - api/artifacts.zip
  rules:
    - changes:
      - api/*

dockerize api:
  stage: dockerize
  image: docker:latest
  script:
    - docker login -u=${DOCKERHUB_USERNAME} -p=${DOCKERHUB_ACCESS_TOKEN}
    - docker build -t ${DOCKERHUB_USERNAME}/job-hunting-tracker-api:latest .
    - docker push ${DOCKERHUB_USERNAME}/job-hunting-tracker-api:latest
  services:
    - docker:dind
  when: manual

deploy heroku:
  stage: deploy
  image: ubuntu
  before_script:
    - cd api/
    - apt-get update -qy
    - apt-get install -y git curl
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  allow_failure: true
  rules:
    - changes:
      - api/*
      - frontend/*